### PR TITLE
Include raw_clonotype_id in DownloadAndAppendTcrClonotypes output

### PR DESCRIPTION
**Pull request by gboggy2**
Update .AppendTcrClonotypes and .ProcessAndAggregateTcrClonotypes to include raw_clonotype_id in output for DownloadAndAppendTcrClonotypes

### CODE REVIEW

**Comment by GWMcElfresh** [comment]
seems fine. the 4.2 version failed because it couldn't download/install scGate. I don't think there's a reason it shouldn't have been able to, so I restarted the job. 

out of curiosity, what are you using raw_clonotype_id for? scRepertoire ?

**Comment by gboggy2** [comment]
> seems fine. the 4.2 version failed because it couldn't download/install scGate. I don't think there's a reason it shouldn't have been able to, so I restarted the job.
> 
> out of curiosity, what are you using raw_clonotype_id for? scRepertoire ?

I am interested in using this to identify cells with the same clonotypes as those in CoNGA clusters.

**Comment by GWMcElfresh** [comment]
> > seems fine. the 4.2 version failed because it couldn't download/install scGate. I don't think there's a reason it shouldn't have been able to, so I restarted the job.
> > out of curiosity, what are you using raw_clonotype_id for? scRepertoire ?
> 
> I am interested in using this to identify cells with the same clonotypes as those in CoNGA clusters.

ah okay. just a heads up: this does have the limitation of failing to identify the same clone in a tissue if the tissue was split into two lanes before sequencing. 

This code addresses that specific problem by relying on the ChainCDR3 column instead, but has the reciprocal issue of "public clones that have a single ChainCDR3 but different raw_clonotype_ids are merged" (but they should have the same conga.clusters_tcr value, so I think that is okay).

``` 
#determine how long the ChainCDR3s are (to filter duplicitously aligned cdr3s)
length_of_chaincdr3s <- unlist(lapply(stringr::str_extract_all(pattern = ",", string = seuratObj@meta.data[, "ChainCDR3s"]), length))

#add length info to metadata
seuratObj@meta.data$length_of_chaincdr3s <- length_of_chaincdr3s

#add conga clusters information based on CDR3
tmp_metadata <- merge(seuratObj@meta.data[length_of_chaincdr3s == 1, ], 
                      seuratObj@meta.data[length_of_chaincdr3s == 1, c("ChainCDR3s", "conga.clusters_tcr")], by = "ChainCDR3s")

**Comment by gboggy2** [comment]
> > > seems fine. the 4.2 version failed because it couldn't download/install scGate. I don't think there's a reason it shouldn't have been able to, so I restarted the job.
> > > out of curiosity, what are you using raw_clonotype_id for? scRepertoire ?
> > 
> > 
> > I am interested in using this to identify cells with the same clonotypes as those in CoNGA clusters.
> 
> ah okay. just a heads up: this does have the limitation of failing to identify the same clone in a tissue if the tissue was split into two lanes before sequencing.
> 
> This code addresses that specific problem by relying on the ChainCDR3 column instead, but has the reciprocal issue of "public clones that have a single ChainCDR3 but different raw_clonotype_ids are merged" (but they should have the same conga.clusters_tcr value, so I think that is okay).
> 
> ```
> #determine how long the ChainCDR3s are (to filter duplicitously aligned cdr3s [length >= 2] or cells with only one chain [length == 0])
> length_of_chaincdr3s <- unlist(lapply(stringr::str_extract_all(pattern = ",", string = seuratObj@meta.data[, "ChainCDR3s"]), length))
> 
> #add length info to metadata
> seuratObj@meta.data$length_of_chaincdr3s <- length_of_chaincdr3s
> 
> #add conga clusters information based on CDR3
> metadata <- merge(seuratObj@meta.data[length_of_chaincdr3s == 1, ], 
>                       seuratObj@meta.data[length_of_chaincdr3s == 1, c("ChainCDR3s", "conga.clusters_tcr")], by = "ChainCDR3s")
> ```

Ah, interesting, thanks. I’ll experiment with your code.

**Comment by gboggy2** [comment]
> @gboggy2: this seems reasonable enough. does what GW posted have any impact on what you would want in this PR?

@bbimber I don’t think so, actually. I think it would be useful to have this ID even if it isn’t best for the use case I had in mind.

**Pull request merged**
